name: Launch and follow workflow
description: Launch a workflow and follow it until it completes
branding:
  icon: 'arrow-circle-up'
  color: 'green'
inputs:
  workflow:
    description: 'The workflow to run'
    required: true
  token:
    description: 'The GitHub token to use for authentication'
    required: true
    default: '${{ github.token }}'
  inputs:
    description: 'The JSON to pass as input to the workflow'
    required: true
    default: '{}'
  ref:
    description: 'The ref to run the workflow from (defaults to main)'
    required: false
    default: 'main'
  repo:
    description: 'The repository to run the workflow in'
    required: true
    default: '${{ github.repository }}'
runs:
  using: composite
  steps:
    - name: run workflow with gh workflow run
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}  
      run: |
        echo '${{ inputs.inputs }}' | gh workflow run ${{ inputs.workflow }} \
        --repo ${{ inputs.repo }} \
        --ref ${{ inputs.ref }} \
        --json
    - run: sleep 5
      shell: bash 
    - name: follow workflow with gh run watch 
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }} 
      run: |
        run_id=$(gh run list \
        --workflow=${{ inputs.workflow }} \
        --limit 1 \
        --json databaseId \
        --jq '.[].databaseId' \
        --repo ${{ inputs.repo }})
        gh run watch "${run_id}" \
        --exit-status \
        --repo "${{ inputs.repo }}"
