name: Launch and follow workflow
description: Launch a workflow and follow it until it completes
branding:
  icon: 'arrow-up-right'
  color: 'green'
inputs:
  workflow:
    description: 'The workflow to run'
    required: true
  token:
    description: 'The GitHub token to use for authentication'
    required: true
    default: '${{ github.token }}'
  inputs:
    description: 'The JSON to pass as input to the workflow'
    required: true
    default: '{}'
  ref:
    description: 'The ref to run the workflow from (defaults to main)'
    required: false
    default: 'main'
  repo:
    description: 'The repository to run the workflow in'
    required: true
    default: '${{ github.repository }}'
  update_interval:
    description: 'The interval to check for updates to the workflow run'
    required: true
    default: 8
  follow_workflow:
    description: 'Whether to follow the workflow run'
    required: true
    default: true
runs:
  using: composite
  steps:
    - name: run workflow with gh workflow run
      shell: bash
      run: |
        echo '${{ inputs.inputs }}' | gh workflow run ${{ inputs.workflow }} \
        --repo ${{ inputs.repo }} \
        --ref ${{ inputs.ref }} \
        --json
      env:
        GITHUB_TOKEN: ${{ inputs.token }} 
    - run: sleep 5
      shell: bash 
    - name: get run id
      id: run
      shell: bash
      run: |
        echo "run_id=$(gh run list \
        --workflow=${{ inputs.workflow }} \
        --limit 1 \
        --json databaseId \
        --jq '.[].databaseId' \
        --repo ${{ inputs.repo }})" > "$GITHUB_OUTPUT"
      env:
        GITHUB_TOKEN: ${{ inputs.token }} 
    - name: print run link
      shell: bash
      run: |
        echo ${{ github.server_url }}/${{ inputs.repo }}/actions/runs/${{ steps.run.outputs.run_id }}
    - name: follow workflow with gh run watch 
      shell: bash
      if: ${{ inputs.follow_workflow }}
      run: |
        gh run watch ${{ steps.run.outputs.run_id }} \
        --exit-status \
        --interval ${{ inputs.update_interval }} \
        --repo "${{ inputs.repo }}"
      env:
        GITHUB_TOKEN: ${{ inputs.token }} 
    - name: print run link
      shell: bash
      run: |
        echo ${{ github.server_url }}/${{ inputs.repo }}/actions/runs/${{ steps.run.outputs.run_id }}
